[SFrame-V3] sframe: gas: translate specific CFI directives for SFRAME_FDE_TYPE_FLEX
This patch updates the SFrame generation in GAS to translate specific
.cfi_escape directives into the new SFrame V3 FDE type
SFRAME_FDE_TYPE_FLEX.

The primary goal is to support code patterns where:
  - the Canonical Frame Address (CFA) is not defined by a simple offset
    from the Stack Pointer (SP) or Frame Pointer (FP), or where the CFA
    rule involves a dereference. Such patterns are generated by compilers
    for stack realignment (e.g., DRAP on x86_64, or when mixing legacy
    codes that keep 4-byte stack alignment with modern codes that keep
    16-byte stack alignment for SSE compatibility).
  - the Frame Pointer is not defined by a simple offset from the CFA,
    but may even involve another register and/or dereferencing.
  - the Return Address is not defined by a simple offset from the CFA,
    but may even involve another register and/or dereferencing.

Support for non-SP/FP based CFA: Update sframe_xlate_do_def_cfa () and
sframe_xlate_do_def_cfa_register () to detect when a non-SP/FP register
is used for the CFA.

Support for CFA expressions: A vital part of supporting the
above-mentioned cases on AMD64 is support for CFA expressions.  Add
sframe_xlate_do_escape_cfa_expr () to parse simple
DW_CFA_def_cfa_expression sequence in .cfi_escape.

Support for FP expressions: Update sframe_xlate_do_escape_expr () to
handle DW_CFA_expression involving DW_OP_breg6 (rbp) on AMD64,
allowing for tracking of the Frame Pointer when it is saved with a
dereference rule in the DRAP pattern.

The "support" for both CFA expressions and FP expressions is quite
minimal, and is tailored to the most commonly seen occurrences generated
by GCC for AMD64.

gas/
	* gas/gen-sframe.c (output_sframe_row_entry_offsets):
	(sframe_xlate_do_def_cfa): Handle non-SP/FP CFA registers by setting
	flex_p for AMD64.
	(sframe_xlate_do_def_cfa_register): Likewise.
	(sframe_xlate_escape_sleb128_to_int64): New definition.
	(sframe_xlate_do_escape_cfa_expr): New function to handle
	DW_CFA_def_cfa_expression of specific shapes.
	(sframe_xlate_do_escape_expr): Update to handle dereferenced FP rules.
	(sframe_xlate_do_cfi_escape): Invoke sframe_xlate_do_escape_cfa_expr ().
	(create_sframe_all): In case of error, but when signal frame is
	also true, there cannot be a flex FDE.

---
[Changes in V1]
  - Admissibility checks need correction.  Remove stale comments [Jan].
  - Fix regression failure on s390x [Jens].
  - Allow sleb128 in the DW_CFA_expression and DW_CFA_def_cfa_expression
    offsets [Jan, Jens].
  - Use a backend hook to allow each ABI/arch to select whether to emit
    flex FDE  [Jens].
[End of changes in V1]

[Changes in V2]
  - Adjust code comment in sframe_xlate_do_def_cfa.  Now that we check
    the hook sframe_support_flex_fde_p (), adjust code comment to simply
    list the example patterns from AMD64, s390x for informational
    purpose [Jens, Indu].
[End of changes in V2]

[No changes in V3]

[Changes in V4]
  - Fix FTBFS on i686.  Read int64_t via read_sleb128_to_int64 and
    typecast to offsetT.
	gas/gen-sframe.c:1713:64: error: passing argument 3 of ‘read_sleb128_to_int64’ from incompatible pointer type [-Werror=incompatible-pointer-types]
	 1713 |       size_t read = read_sleb128_to_int64 (buf_start, buf_end, &offset);
	      |                                                                ^~~~~~~
	      |                                                                |
	      |                                                                offsetT * {aka int *}
	In file included from gas/gen-sframe.c:27:
	gas/../include/leb128.h:88:33: note: expected ‘int64_t *’ {aka ‘long long int *’} but argument is of type ‘offsetT *’ {aka ‘int *’}
	   88 |                        int64_t *r)
	      |                        ~~~~~~~~~^
	In function ‘read_sleb128_to_int64’,
	    inlined from ‘sframe_xlate_escape_sleb128_to_int64.isra’ at gas/gen-sframe.c:1713:21:
	gas/../include/leb128.h:109:6: error: array subscript ‘int64_t {aka long long int}[0]’ is partly outside array bounds of ‘
	offsetT[1]’ {aka ‘int[1]’} [-Werror=array-bounds]
	  109 |   *r = result;
	      |   ~~~^~~~~~~~
	gas/gen-sframe.c: In function ‘sframe_xlate_escape_sleb128_to_int64.isra’:
	gas/gen-sframe.c:1700:11: note: object ‘offset’ of size 4
	 1700 |   offsetT offset = 0;
	      |           ^~~~~~
	cc1: all warnings being treated as errors
[End of changes in V4]