sim/m32c: Add missing include getopt.h in main.c
On buildbot gdb-centos-x86_64 we run into:
...
sim/m32c/main.c: In function ‘main’:
sim/m32c/main.c:143:3: error: implicit declaration of function ‘getopt’ \
  [-Werror=implicit-function-declaration]
   while ((o = getopt (argc, argv, "tc:vdm:C")) != -1)
   ^
cc1: all warnings being treated as errors
make[3]: *** [main.o] Error 1
...

Fix this by adding the missing include of getopt.h.

Build on x86_64-linux.