Fix the strrchr error for DOS based filesystem
Fix the strrchr error like:

gprof/source.c:130:28: error: initialization discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
  130 |             char *bslash = strrchr (sf->name, '\\');

binutils/

	PR binutils/34125
	* bucomm.c (template_in_dir): Make bslash const char *.

gprof/

	PR binutils/34125
	* source.c (annotate_source): Make bslash const char *.

Signed-off-by: H.J. Lu <hjl.tools@gmail.com>
(cherry picked from commit 365fc34606d2d566855e8ba3db9c4f7986ed3bcc)