Include <array> in ui-style.h
ui-style.h uses std::array without including <array> directly.

This builds successfully with GCC 8 and libstdc++ as its <tuple> header
includes <array>. However, libc++'s <tuple> does not include <array> with
Apple Clang 13.0.0. This causes the GDB builds to fail on macOS with:

	error: implicit instantiation of undefined template
	'std::array<unsigned char, 3>'

Include <array> directly in ui-style.h rather than relying on the
include from <tuple>.

Approved-By: Andrew Burgess <aburgess@redhat.com>
(cherry picked from commit 625a5c311e6df32aa28214d017c65303bb5d6451)