readelf/objdump: support for SFrame section
[No changes in V4]

[Changes in V3]
  - Minor changes to uptake API signature changes in libsframe.
  - Fixed -Wformat warnings in dump_sframe_func_with_fres ().
[End of changes in V3]

[Changes in V2]
  - Fixed compilation errors seen on i686.
  - readelf: bugfix: --sframe=.eh_frame gives no error
    New behaviour:
    $ readelf --sframe=.eh_frame <Program>
    readelf: Error: SFrame decode failure: Buffer does not contain SFrame data.
    $ readelf --sframe=.foo <Program>
    readelf: Warning: Section '.foo' was not dumped because it does not exist
  - readelf: make --sframe arguments optional (similar to the command
    line option for objdump)
[End of changes in V2]

This patch adds support for SFrame in readelf and objdump.

include/ChangeLog:

	* sframe-api.h (dump_sframe): New function declaration.

ChangeLog:

	* binutils/Makefile.am: Add dependency on libsframe for
	readelf and objdump.
	* binutils/Makefile.in: Regenerate.
	* binutils/doc/binutils.texi: Document --sframe=[section].
	* binutils/doc/sframe.options.texi: New file.
	* binutils/objdump.c: Add support for SFrame format.
	* binutils/readelf.c: Likewise.
	* include/sframe-api.h: Add new API for dumping .sframe
	section.
	* libsframe/Makefile.am: Add sframe-dump.c.
	* libsframe/Makefile.in: Regenerate.
	* libsframe/sframe-dump.c: New file.