Use TOLOWER in SYMBOL_HASH_NEXT
The ABI tags patch will add a use of SYMBOL_HASH_NEXT in cp-support.c,
which fails to compile with:

  src/gdb/cp-support.c:38:0:
  src/gdb/cp-support.c: In function ‘unsigned int cp_search_name_hash(const char*)’:
  src/gdb/../include/safe-ctype.h:148:20: error: ‘do_not_use_tolower_with_safe_ctype’ was not declared in this scope
   #define tolower(c) do_not_use_tolower_with_safe_ctype
		      ^
  src/gdb/minsyms.h:174:18: note: in expansion of macro ‘tolower’
     ((hash) * 67 + tolower ((unsigned char) (c)) - 113)
		    ^
  src/gdb/cp-support.c:1677:14: note: in expansion of macro ‘SYMBOL_HASH_NEXT’
	 hash = SYMBOL_HASH_NEXT (hash, *string);
		^

This fixes the problem before it happens.

gdb/ChangeLog:
yyyy-mm-dd  Pedro Alves  <palves@redhat.com>

     * dictionary.c: Include "safe-ctype.h".
     * minsyms.c: Include "safe-ctype.h".
     * minsyms.c (SYMBOL_HASH_NEXT): Use TOLOWER instead of tolower.