readelf.c gcc-4.9 compile error
gcc-4.9 doesn't like an empty initialiser.

binutils/readelf.c: In function ‘process_relocs’:
binutils/readelf.c:10229:5: error: missing initializer for field ‘sh_name’ of ‘Elf_Internal_Shdr’ [-Werror=missing-field-initializers]
     Elf_Internal_Shdr section = {};

	* readelf.c (process_relocs): Avoid gcc-4.9 compile error.

(cherry picked from commit 4643afba9100939b16f50e13f085fc5bd0284930)