binutils: fix C23 -Wdiscarded-qualifiers errors
When compiling with gcc 15, I get these:

      CC       prdbg.o
    /home/simark/src/binutils-gdb/binutils/prdbg.c: In function â€˜tg_start_functionâ€™:
    /home/simark/src/binutils-gdb/binutils/prdbg.c:2658:11: error: assignment discards â€˜constâ€™ qualifier from pointer target type [-Werror=discarded-qualifiers]
     2658 |       sep = strchr (name, '(');
          |           ^
    cc1: all warnings being treated as errors
    make[2]: *** [Makefile:1220: prdbg.o] Error 1
      CC       addr2line.o
    /home/simark/src/binutils-gdb/binutils/addr2line.c: In function â€˜translate_addressesâ€™:
    /home/simark/src/binutils-gdb/binutils/addr2line.c:390:21: error: assignment discards â€˜constâ€™ qualifier from pointer target type [-Werror=discarded-qualifiers]
      390 |                   h = strrchr (filename, '/');
          |                     ^
    cc1: all warnings being treated as errors
    make[2]: *** [Makefile:1220: addr2line.o] Error 1
      CC       nm.o
    /home/simark/src/binutils-gdb/binutils/nm.c: In function â€˜print_symnameâ€™:
    /home/simark/src/binutils-gdb/binutils/nm.c:689:21: error: initialization discards â€˜constâ€™ qualifier from pointer target type [-Werror=discarded-qualifiers]
      689 |       char *atver = strchr (name, '@');
          |                     ^~~~~~
    cc1: all warnings being treated as errors

I think they are related to the fact that strchr having changed to
return const when passed a const.

This partially fixes PR binutils/34125.

Change-Id: Idb829916378f0a18e717d1e80414aaa5eba4f7f0
(cherry picked from commit 9cb12adfb54bc3dabf4ee00296064245eb7660ef)