loongarch gcc-4.9 build error
gas/config/tc-loongarch.c: In function ‘md_apply_fix’:
gas/config/tc-loongarch.c:1886:7: error: a label can only be part of a statement and a declaration is not a statement
       unsigned int subtype;
       ^

	* config/tc-loongarch.c (md_apply_fix <BFD_RELOC_LARCH_CFA>):
	Avoid gcc-4.9 error.

(cherry picked from commit d36b7ef85a30cda5ea19110920f61727be2fd984)