libtool.m4: adjust kludge for ignoring syntax errors
LT_PATH_NM considers an nm to support -p/-B if it returns
output that names the path being checked -- but since that is itself nm
(usually with a path attached), this can trigger false positives with
errors like

/usr/bin/nm: unknown option "B" ignored"

The test currently avoids this case for the single instance of HP-UX
by deleting all but the last line of the output.  Keep on doing that
(so we don't do more work than we need to), but also explicitly
eliminate references to "unknown" and "invalid", with any leading
capitalization.  This handles Darwin, which says

error: nm: invalid argument '-B'

Alas, we cannot check the exit code, because some nm's return nonzero
exit codes if no symbols are found!

Things were also erroneously failing if nm had actual symbols in it,
because we were getting output that did not mention nm by name (its
usual output).  Identify things that look like valid nm output and
let it through.

	PR libctf/29547
	* libtool.m4 (LT_PATH_NM): Explicitly filter out 'unknown'
	and 'invalid' errors when looking for valid output.  Let
	through actual valid nm output too.